/*
 * Created on 2022-11-15 ( Time 13:29:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

const Symbols = {
    IBulletinBoardService: Symbol.for('IBulletinBoardService'),
    IBulletinBoardController: Symbol.for('IBulletinBoardController'),
    IBulletinBoardRepository: Symbol.for('IBulletinBoardRepository'),

    IAuthenticationController: Symbol.for('IAuthenticationController'),
    IAuthenticationService: Symbol.for('IAuthenticationService'),
    IAuthenticationRepository: Symbol.for('IAuthenticationRepository'),


    IPersonInfoController: Symbol.for('IPersonInfoController'),
    IPersonInfoService: Symbol.for('IPersonInfoService'),

    IAuthorisedRepController: Symbol.for('IAuthorisedRepController'),
    IAuthorisedRepService: Symbol.for('IAuthorisedRepService'),
    
    IAccountInfoController: Symbol.for('IAccountInfoController'),
    IAccountInfoService: Symbol.for('IAccountInfoService'),
    IRemoveAccountService: Symbol.for('IRemoveAccountService'),

    IEcrsController: Symbol.for('IEcrsController'),
    IEcrsService: Symbol.for('IEcrsService'),


    ISessionService: Symbol.for('ISessionService'),
    ISessionRepository: Symbol.for('ISessionRespoitory'),


};

export { Symbols };




